import React, { useState } from 'react';
import {
  Bell,
  AlertTriangle,
  TrendingUp,
  MapPin,
  CheckCircle2,
  Share2,
  Filter,
  FileSpreadsheet,
  ShieldCheck,
} from 'lucide-react';
import { EpidemiologicalIntelligence, LiveAlert, ActivePage } from '../types';

interface AlertCenterProps {
  intelligence: EpidemiologicalIntelligence;
  totalRecords: number;
  onSelectPage: (page: ActivePage) => void;
  onLoadSample: () => void;
}

export const AlertCenter: React.FC<AlertCenterProps> = ({
  intelligence,
  totalRecords,
  onSelectPage,
  onLoadSample,
}) => {
  const [filterLevel, setFilterLevel] = useState<'all' | 'critical' | 'high' | 'medium'>('all');
  const [acknowledgedIds, setAcknowledgedIds] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);

  const { liveAlerts, highRiskZonesCount } = intelligence;

  if (totalRecords === 0) {
    return (
      <div className="space-y-6 pb-16">
        <div>
          <h1 className="text-2xl font-black text-white font-mono">Alert Center</h1>
          <p className="text-xs text-slate-400 font-mono">Automated triage & outbreak risk notifications</p>
        </div>

        <div className="p-12 rounded-3xl bg-[#080c18] border border-slate-800 text-center max-w-xl mx-auto space-y-4">
          <div className="w-14 h-14 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-400 mx-auto flex items-center justify-center">
            <Bell className="w-7 h-7" />
          </div>
          <h2 className="text-lg font-bold text-white font-mono">No Active Alerts</h2>
          <p className="text-xs text-slate-400 font-mono leading-relaxed">
            Upload surveillance records or load the sample Tamil Nadu dataset to generate real-time Critical, High, and Medium outbreak alerts.
          </p>
          <div className="flex justify-center gap-3 pt-2">
            <button
              onClick={onLoadSample}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 font-bold text-xs font-mono shadow-lg shadow-cyan-500/20 transition active:scale-95"
            >
              <FileSpreadsheet className="w-4 h-4" />
              Load Sample Dataset
            </button>
            <button
              onClick={() => onSelectPage('upload')}
              className="px-5 py-2.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 font-medium text-xs font-mono hover:bg-slate-800 transition"
            >
              Upload CSV
            </button>
          </div>
        </div>
      </div>
    );
  }

  const filteredAlerts = liveAlerts.filter((alert) => {
    if (acknowledgedIds.includes(alert.id)) return false;
    if (filterLevel === 'all') return true;
    if (filterLevel === 'critical') return alert.level === 'critical';
    if (filterLevel === 'high') return alert.level === 'high';
    if (filterLevel === 'medium') return alert.level === 'medium';
    return true;
  });

  const criticalCount = liveAlerts.filter((a) => a.level === 'critical').length;
  const highCount = liveAlerts.filter((a) => a.level === 'high').length;
  const mediumCount = liveAlerts.filter((a) => a.level === 'medium').length;

  const handleAcknowledge = (id: string) => {
    setAcknowledgedIds((prev) => [...prev, id]);
  };

  const handleShareBulletin = () => {
    const text = `OUTBREAKX ALERT BULLETIN (${new Date().toISOString().split('T')[0]})\n` +
      liveAlerts.map((a, i) => `${i + 1}. [${a.level.toUpperCase()}] ${a.title} - ${a.metric}`).join('\n') +
      '\nGenerated by OUTBREAKX Epidemiological Intelligence';

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 rounded-3xl bg-[#070913] border border-slate-800 backdrop-blur-xl">
        <div>
          <div className="flex items-center gap-2">
            <Bell className="w-5 h-5 text-rose-400" />
            <h1 className="text-xl sm:text-2xl font-black tracking-tight text-white font-mono">
              Outbreak Alert Center
            </h1>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Critical, High, and Medium outbreak notifications derived from verified transmission clusters
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleShareBulletin}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 hover:border-cyan-500/30 text-xs font-mono text-slate-200 transition"
          >
            <Share2 className="w-3.5 h-3.5 text-cyan-400" />
            <span>{copied ? 'Copied Bulletin!' : 'Copy Alert Bulletin'}</span>
          </button>
        </div>
      </div>

      {/* Priority Filter Tabs */}
      <div className="flex flex-wrap items-center gap-2 p-1.5 rounded-2xl bg-slate-900/80 border border-slate-800 text-xs font-mono">
        <button
          onClick={() => setFilterLevel('all')}
          className={`px-3.5 py-1.5 rounded-xl transition ${
            filterLevel === 'all'
              ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 font-bold'
              : 'text-slate-400 hover:text-white'
          }`}
        >
          All Alerts ({liveAlerts.length})
        </button>

        <button
          onClick={() => setFilterLevel('critical')}
          className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl transition ${
            filterLevel === 'critical'
              ? 'bg-rose-500 text-white font-bold'
              : 'text-rose-400 hover:bg-rose-500/10'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-rose-500" />
          Critical Alerts ({criticalCount})
        </button>

        <button
          onClick={() => setFilterLevel('high')}
          className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl transition ${
            filterLevel === 'high'
              ? 'bg-orange-500 text-white font-bold'
              : 'text-orange-400 hover:bg-orange-500/10'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-orange-500" />
          High Alerts ({highCount})
        </button>

        <button
          onClick={() => setFilterLevel('medium')}
          className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl transition ${
            filterLevel === 'medium'
              ? 'bg-amber-500 text-slate-950 font-bold'
              : 'text-amber-400 hover:bg-amber-500/10'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-amber-400" />
          Medium Alerts ({mediumCount})
        </button>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="p-8 rounded-2xl bg-[#080c18] border border-slate-800 text-center text-xs font-mono text-slate-400">
            No active alerts matching the selected filter.
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const isCritical = alert.level === 'critical';
            const isHigh = alert.level === 'high';

            let borderStyle = 'border-amber-500/30 bg-amber-500/5';
            let badgeBg = 'bg-amber-500/20 text-amber-300 border-amber-500/40';
            let dotColor = 'bg-amber-400';

            if (isCritical) {
              borderStyle = 'border-rose-500/40 bg-rose-500/10';
              badgeBg = 'bg-rose-500/20 text-rose-300 border-rose-500/40';
              dotColor = 'bg-rose-400 animate-ping';
            } else if (isHigh) {
              borderStyle = 'border-orange-500/35 bg-orange-500/10';
              badgeBg = 'bg-orange-500/20 text-orange-300 border-orange-500/40';
              dotColor = 'bg-orange-400';
            }

            return (
              <div
                key={alert.id}
                className={`p-5 rounded-2xl border transition-all ${borderStyle} space-y-3`}
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2.5">
                    <span className={`w-2.5 h-2.5 rounded-full ${dotColor}`} />
                    <h3 className="text-base font-bold text-white font-mono">
                      {alert.title}
                    </h3>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className={`px-2.5 py-0.5 rounded text-[10px] font-mono font-bold uppercase border ${badgeBg}`}>
                      {alert.level} Alert
                    </span>
                    <button
                      onClick={() => handleAcknowledge(alert.id)}
                      className="px-2.5 py-0.5 rounded text-[10px] font-mono text-slate-400 hover:text-slate-200 hover:bg-slate-800/80 border border-slate-700 transition"
                      title="Acknowledge Alert"
                    >
                      Dismiss
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs font-mono">
                  <div className="flex items-center gap-1.5 text-slate-300">
                    <MapPin className="w-3.5 h-3.5 text-purple-400" />
                    <span>Location: <strong>{alert.location}</strong></span>
                  </div>

                  <div className="flex items-center gap-1.5 text-slate-300">
                    <TrendingUp className="w-3.5 h-3.5 text-cyan-400" />
                    <span>Vector: <strong>{alert.disease}</strong></span>
                  </div>

                  <div className="text-slate-400 truncate">
                    Status: <strong className="text-white">{alert.metric}</strong>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-[#05070e] border border-slate-800/80 text-xs font-mono text-slate-300">
                  <strong className="text-cyan-400">Directive: </strong>
                  {alert.recommendation}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
